name: Build LiteLoader ToolChain

on: [ push ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1     

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        id: build
        run: |
          MSBuild.exe ./LLPeEditor.sln -property:Configuration=Release -property:Configuration=Js
        shell: bash

      - name: Copy Upload Files
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir Upload
          cp x64/Release/LLPeEditor.pdb Upload
          cp x64/Release/LLPeEditor.exe Upload
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: LiteLoader
          path: ${{ github.workspace }}\Upload