name: Build
env:
  ZIP_SHA256: ""
  EXE_SHA256: ""
  PDB_SHA256: ""
on:
  release:
    types:
      - created
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "xmake.lua"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - name: Update XMake Repository
        run: xmake repo -u

      - name: Build PeEditor
        run: |
          xmake f -p windows -m release -a x64 --ccache=n -y
          xmake -w -y

      - name: Prepare Artifacts
        run: |
          mkdir artifacts
          cp build/windows/x64/release/PeEditor.exe artifacts
          cp build/windows/x64/release/PeEditor.pdb artifacts
          mv artifacts peeditor-windows-x64
          mkdir artifacts
          mv peeditor-windows-x64 artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: peeditor-windows-x64
          path: artifacts

  upload-to-release:
    name: Upload to Release
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Compress Artifacts
        id: compress
        run: |
          mv peeditor-windows-x64 artifacts
          mv artifacts/peeditor-windows-x64 .
          cd peeditor-windows-x64
          zip -r ../peeditor-windows-x64.zip *
          cd ..
          echo "ZIP_SHA256=$(sha256sum peeditor-windows-x64.zip | cut -d ' ' -f 1)" >> $GITHUB_ENV
          echo "EXE_SHA256=$(sha256sum peeditor-windows-x64/PeEditor.exe | cut -d ' ' -f 1)" >> $GITHUB_ENV
          echo "PDB_SHA256=$(sha256sum peeditor-windows-x64/PeEditor.pdb | cut -d ' ' -f 1)" >> $GITHUB_ENV
        shell: bash

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            peeditor-windows-x64.zip
            peeditor-windows-x64/PeEditor.exe
            peeditor-windows-x64/PeEditor.pdb
          body: |
            ---
            | File                                          | SHA256                |
            | :-------------------------------------------- | :-------------------- |
            | peeditor-windows-x64.zip                      | ${{ env.ZIP_SHA256 }} |
            | PeEditor.exe                                  | ${{ env.EXE_SHA256 }} |
            | PeEditor.pdb                                  | ${{ env.PDB_SHA256 }} |
