name: Build LiteLoader ToolChain

on: [ push ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1  

      - name: Setup LibClang   
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          wget https://ziglang.org/deps/llvm%2bclang%2blld-13.0.1-x86_64-windows-msvc-release-mt.tar.xz -O LibClang.tar.xz
          7z e LibClang.tar.xz
          7z x LibClang.tar
        shell: bash

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        id: build
        run: |
          MSBuild.exe ./LLPeEditor.sln -property:Configuration=Release
        shell: bash

      - name: Copy Upload Files
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir Upload
          cp x64/Release/LLPeEditor.pdb Upload
          cp x64/Release/LLPeEditor.exe Upload
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ToolChain_PE_Editor
          path: ${{ github.workspace }}\Upload