name: Build

on:
  release:
    types:
      - created
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "xmake.lua"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v5
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - name: Update XMake Repository
        run: xmake repo -u

      - name: Build PeEditor
        run: |
          xmake f -p windows -m release -a x64 --ccache=n -y
          xmake -y

      - name: Prepare Artifacts
        run: |
          mkdir artifacts
          cp build/windows/x64/release/PeEditor.exe artifacts
          cp build/windows/x64/release/PeEditor.pdb artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: peeditor-windows-x64
          path: artifacts

  upload-to-release:
    name: Upload to Release
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: peeditor-windows-x64
          path: artifacts

      - name: Compress Artifacts
        id: compress
        run: |
          cd artifacts
          zip -r ../peeditor-windows-x64.zip *
        shell: bash

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.zip
            artifacts/*.exe
            artifacts/*.pdb
